#!/usr/bin/env node
const fs = require("node:fs");
const vm = require("node:vm");

const [inputPath, outputPath] = process.argv.slice(2);
if (!inputPath || !outputPath) {
  console.error(
    "usage: node crates/pi-ai/tools/generate_models.cjs <models.generated.ts> <models_generated.rs>",
  );
  process.exit(2);
}

let source = fs.readFileSync(inputPath, "utf8");
source = source.replace(/^import type .*$/gm, "");
source = source.replace(/export const MODELS\s*=\s*/, "const MODELS = ");
source = source.replace(/\s+satisfies\s+Model<[^>]+>/g, "");
source = source.replace(/\s+as\s+const\s*;?\s*/g, ";\n");
source += "\nMODELS;";

const models = vm.runInNewContext(source, {}, { filename: inputPath });

function rustString(value) {
  return JSON.stringify(String(value));
}

function jsonValue(value) {
  return value === undefined
    ? "None"
    : `Some(serde_json::json!(${JSON.stringify(value)}))`;
}

function modelInput(values) {
  return `vec![${values
    .map((v) => (v === "image" ? "ModelInput::Image" : "ModelInput::Text"))
    .join(", ")}]`;
}

function rustFloat(value) {
  const n = Number(value || 0);
  return Number.isInteger(n) ? `${n}.0` : `${n}`;
}

const out = [];
out.push("// This file is generated by tools/generate_models.cjs.");
out.push("// Do not edit by hand.");
out.push("use crate::types::{Model, ModelCost, ModelInput};");
out.push("");
out.push("pub fn generated_models() -> Vec<Model> {");
out.push("    vec![");

for (const provider of Object.keys(models).sort()) {
  for (const id of Object.keys(models[provider]).sort()) {
    const m = models[provider][id];
    out.push("        Model {");
    out.push(`            id: ${rustString(m.id)}.into(),`);
    out.push(`            name: ${rustString(m.name)}.into(),`);
    out.push(`            api: ${rustString(m.api)}.into(),`);
    out.push(`            provider: ${rustString(m.provider)}.into(),`);
    out.push(`            base_url: ${rustString(m.baseUrl)}.into(),`);
    out.push(`            reasoning: ${Boolean(m.reasoning)},`);
    out.push(
      `            thinking_level_map: ${jsonValue(m.thinkingLevelMap)},`,
    );
    out.push(`            input: ${modelInput(m.input || ["text"])},`);
    out.push("            cost: ModelCost {");
    out.push(
      `                input: ${rustFloat(m.cost?.input)},`,
    );
    out.push(
      `                output: ${rustFloat(m.cost?.output)},`,
    );
    out.push(
      `                cache_read: ${rustFloat(m.cost?.cacheRead)},`,
    );
    out.push(
      `                cache_write: ${rustFloat(m.cost?.cacheWrite)},`,
    );
    out.push("            },");
    out.push(
      `            context_window: ${Number(m.contextWindow || 0)},`,
    );
    out.push(`            max_tokens: ${Number(m.maxTokens || 0)},`);
    out.push(`            headers: ${jsonValue(m.headers)},`);
    out.push(`            compat: ${jsonValue(m.compat)},`);
    out.push("        },");
  }
}

out.push("    ]");
out.push("}");
out.push("");

fs.writeFileSync(outputPath, out.join("\n"));
